<section class="teaser"></section>

<section class="section py-4">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 col-md-8">
                <section class="promo">
                    <h1 class="font-weight-light"><?= $this->translate('Studievereniging GEWIS') ?></h1>
                    <p class="lead">
                        <?= $this->translate('Welcome to the website of Study association GEWIS, the study association of the department of Mathematics & Computer Science of the Eindhoven University of Technology.') ?>
                    </p>
                </section>
                <section class="news">
                    <h2><?= $this->translate('News') ?></h2>
                    <?php foreach ($news as $item): ?>
                        <article class="content-article">
                            <h3>
                                <?php
                                // TODO: Fix design and URLs
                                $lang = $this->plugin('translate')->getTranslator()->getLocale();
                                if ($item instanceof \Activity\Model\Activity) {
                                    echo ($lang === 'en') ? $item->getNameEn() : $item->getName();
                                } else {
                                    echo ($lang === 'en') ? $item->getEnglishTitle() : $item->getDutchTitle();
                                }
                                ?>
                            </h3>
                            <div style="position: relative; overflow: hidden;">
                                <div class="reveal reveal-10">
                                    <?php
                                    if ($item instanceof \Activity\Model\Activity) {
                                        $content = ($lang === 'en') ? $item->getDescriptionEn() : $item->getDescription();
                                    } else {
                                        $content = ($lang === 'en') ? $item->getEnglishContent() : $item->getDutchContent();
                                    }

                                    echo $this->markdown($content);
                                    ?>
                                    <a class="reveal-button"><?= $this->translate('Continue reading') ?></a>
                                </div>
                            </div>
                        </article>
                        <?php if (!isset($bannerShown)): ?>
                            <article class="content-article">
                                <?php if ($companyBanner !== null): ?>
                                    <?= $this->partial('partial/banner.phtml', ['banner' => $companyBanner]) ?>
                                <?php endif ?>
                            </article>
                        <?php endif; $bannerShown = true; ?>
                    <?php endforeach; ?>

                    <script>
                        $(".reveal-button").click(function () {
                            $(this).parent().addClass("revealed");
                        });
                    </script>
                </section>
                <?php if (!empty($birthdays) && $this->acl('decision_acl')->isAllowed('member', 'birthdays')): ?>
                    <section class="birthdays">
                        <div class="card border-0 rounded-0 mb-4 overflow-hidden">
                            <div class="row">
                                <?php if (!is_null($birthdayTag)): ?>
                                    <div class="col-md-4">
                                        <a href="<?= $this->url('photo/photo', ['photo_id' => $birthdayTag->getPhoto()->getId()]); ?>">
                                            <img class="card-img" src="<?= $this->fileUrl($birthdayTag->getPhoto()->getLargeThumbPath()) ?>" alt="">
                                        </a>
                                    </div>
                                <?php endif; ?>
                                <div class="col-md-<?= is_null($birthdayTag) ? '12' : '8' ?>">
                                    <div class="card-body h-100">
                                        <h4 class="card-title"><?= $this->translate('Verjaardagen') ?></h4>
                                        <ul>
                                            <?php foreach ($birthdays as $birthday): ?>
                                                <li class="card-text"><?= sprintf($this->translate('%s wil be %s years old today!'), $birthday['member']->getFullName(), $birthday['age']) ?></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                <?php endif; ?>
            </div>

            <aside class="col-sm-5 col-md-4">
                <div class="card border-0 rounded-0 mb-4 overflow-hidden">
                    <div class="card-header border-0 rounded-0">
                        <h4 class="card-title"><?= $this->translate('Agenda') ?></h4>
                    </div>
                    <?php if (!empty($activities)): ?>
                        <div class="list-group">
                            <?php foreach ($activities as $activity): ?>
                                <a class="list-group-item" href="<?= $this->url('activity/view', ['id' => $activity->getId()]) ?>">
                                    <h4 class="list-group-item-heading"><?= $activity->getNameEn() ?></h4>
                                    <p class="list-group-item-text text-muted"><?= ucfirst($this->dateFormat($activity->getBeginTime(), IntlDateFormatter::FULL, IntlDateFormatter::SHORT)); ?></p>
                                </a>
                            <?php endforeach; ?>
                        </div>
                    <?php  endif; ?>
                    <div class="card-body">
                        <p class="small">
                            <?= sprintf(
                                $this->translate('Donderdags is er %sborrel%s van 16.30 tot 19.00 uur.'),
                                '<a href="~bac">',
                                '</a>'
                            )
                            ?>
                        </p>
                    </div>
                    <div class="card-footer border-0 rounded-0">
                        <a href="<?= $this->url('activity') ?>" class="card-link"><?= $this->translate('Complete agenda') ?></a>
                        <a href="https://www.google.com/calendar/embed?src=v23gq10ij44fhdsfdof1s613ak%40group.calendar.google.com&gsessionid=OK" class="card-link">iCal</a>
                    </div>
                </div>

                <?php if (!is_null($weeklyPhoto)): ?>
                    <div class="card border-0 rounded-0 mb-4 overflow-hidden">
                        <div class="card-body">
                            <h4 class="card-title"><?= $this->translate('Photo of the week') ?></h4>
                            <a href="<?= $this->url('photo/photo', ['photo_id' => $weeklyPhoto->getPhoto()->getId()]); ?>" class="stretched-link"></a>
                        </div>
                        <img src="<?= $this->fileUrl($weeklyPhoto->getPhoto()->getLargeThumbPath()) ?>" class="card-img-bottom" alt="">
                    </div>
                <?php endif; ?>
                <?php if($this->acl('decision_acl')->isAllowed('member', 'birthdays')): ?>
                    <div class="card border-0 rounded-0 mb-4 overflow-hidden">
                        <div class="card-header border-0 rounded-0">
                            <h4 class="card-title"><?= $this->translate('Infima') ?></h4>
                        </div>
                        <div class="card-body">
                            <?= $this->infima() ?>
                        </div>
                    </div>
                <?php endif ?>
                <div class="card border-0 rounded-0 mb-4 overflow-hidden">
                    <div class="card-header border-0 rounded-0">
                        <h4 class="card-title"><?= $this->translate('Poll') ?></h4>
                    </div>
                    <?php if (isset($poll['poll'])): ?>
                        <div class="card-body">
                            <?= $this->partial('partial/poll.phtml', [
                                'poll' => $poll['poll'],
                                'canVote' => $poll['canVote'],
                                'userVote' => $poll['userVote'],
                                'showResults' => false
                            ]) ?>
                        </div>
                        <div class="card-footer">
                            <a href="<?= $this->url('poll') ?>" class="card-footer__link">
                                <?= $this->translate('View the results') ?>
                            </a>
                        </div>
                    <?php else: ?>
                        <div class="card-body">
                            <?= $this->translate('There currently is no poll.'); ?>
                        </div>
                        <div class="card-footer border-0 rounded-0">
                            <a href="<?= $this->url('poll/request') ?>" class="card-link"><?= $this->translate('Request poll') ?></a>
                            <a href="<?= $this->url('poll/history') ?>" class="card-link"><?= $this->translate('Old polls') ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </aside>
        </div>
    </div>
</section>
