<?php
$lang = $this->plugin('translate')->getTranslator()->getLocale();
?>
<?php if($this->identity()): ?>
    <?php if(in_array($this->identity()->getMember()->getLidnr(), [8073, 8284, 8090, 8329, 8032, 7571, 8186])): ?>
        <style>
            .rainbow {
                background: linear-gradient(to right, red,orange,yellow,green,blue,indigo,violet);
                background-size: 5000% 100%;

                -webkit-animation: AnimationName 10s ease infinite;
                -moz-animation: AnimationName 10s ease infinite;
                animation: AnimationName 10s ease infinite;
            }

            @-webkit-keyframes AnimationName {
                0%{background-position:0% 50%}
                50%{background-position:100% 50%}
                100%{background-position:0% 50%}
            }
            @-moz-keyframes AnimationName {
                0%{background-position:0% 50%}
                50%{background-position:100% 50%}
                100%{background-position:0% 50%}
            }
            @keyframes AnimationName {
                0%{background-position:0% 50%}
                50%{background-position:100% 50%}
                100%{background-position:0% 50%}
            }
        </style>
    <?php endif ?>
<?php endif ?>
<nav class="navbar navbar-expand-lg navbar-gewis bg-gewis" role="navigation">
    <div class="container">
        <a href="<?= $this->url('home') ?>" class="navbar-brand mr-0">
            <span class="gi gewis-base"></span>
        </a>
        <div class="d-flex flex-row order-2 order-lg-3">
            <ul class="navbar-nav flex-row">
                <?php if (null === $this->identity()): ?>
                    <li class="nav-item no-collapse">
                        <a href="<?= $this->url('user') ?>" class="nav-link">
                            <span class="fas fa-user"></span>
                            <span class="sr-only"><?= $this->translate('Login') ?></span>
                        </a>
                    </li>
                <?php else: ?>
                    <?php $member = $this->identity()->getMember() ?>
                    <li class="nav-item dropdown no-collapse">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <?= $member->getFirstName() ?>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="<?= $this->url('member/self') ?>"><?= $this->translate('My information') ?></a>
                            <a class="dropdown-item" href="https://gewis.nl/susos/account/websitelogin.php"><?= $this->translate('SuSOS') ?></a>
                            <a class="dropdown-item" href="<?= $this->url('user/default', ['action' => 'password']) ?>"><?= $this->translate('Change password') ?></a>
                            <?php if ($this->acl('decision_acl')->isAllowed('organ', 'edit')): ?>
                                <a class="dropdown-item" href="<?= $this->url('admin') ?>"><?= $this->translate('Admin') ?></a>
                            <?php endif; ?>
                            <hr class="dropdown-divider">
                            <a class="dropdown-item" href="<?= $this->url('user/default', ['action' => 'logout']) ?>"><?= $this->translate('Logout') ?></a>
                        </div>
                    </li>
                <?php endif; ?>
                <li class="nav-item dropdown no-collapse">
                    <a href="#" class="nav-link dropdown-toggle" role="button" id="languagesDropdown" data-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-globe-europe"></i>
                        <span class="sr-only"><?= $this->translate('Language settings') ?></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right language <?= ($lang == 'en') ? 'reverse' : ''?>" aria-labelledby="languagesDropdown">
                        <a class="dropdown-item <?= ($lang == 'en') ? 'disabled' : '' ?>" href="<?= $this->url('lang', ['lang' => 'en']) ?>">
                            <span class="flag-icon flag-icon-en" style="background-image: url('<?= $this->basePath() ?>/img/en.svg');"></span>English
                        </a>
                        <a class="dropdown-item <?= ($lang == 'nl') ? 'disabled' : '' ?>" href="<?= $this->url('lang', ['lang' => 'nl']) ?>">
                            <span class="flag-icon flag-icon-nl" style="background-image: url('<?= $this->basePath() ?>/img/nl.svg');"></span>Nederlands
                        </a>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse order-3 order-lg-2" id="navbarToggle">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown <?= $this->moduleIsActive(['frontpage', 'page']) ? 'active default' : '' ?>">
                    <a href="#" class="nav-link dropdown-toggle d-lg-none" role="button" id="associationDropdown" data-toggle="dropdown" aria-expanded="false">
                        <?= $this->translate('Association') ?>
                    </a>
                    <a href="<?= $this->url('home/page', ['category' => 'vereniging']) ?>" class="nav-link dropdown-hover d-none d-lg-block" role="button">
                        <?= $this->translate('Association') ?>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="associationDropdown">
                        <a class="dropdown-item d-lg-none" href="<?= $this->url('home/page', ['category' => 'vereniging']) ?>"><?= $this->translate('Association') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'av']) ?>"><?= $this->translate('General Meeting') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'bestuur']) ?>"><?= $this->translate('Board 2015/2016') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/committee_list') ?>"><?= $this->translate('Committees') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/fraternity_list') ?>"><?= $this->translate('Fraternities') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'lied']) ?>"><?= $this->translate('GEWIS song') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'statuten']) ?>"><?= $this->translate('Regulations') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/page', ['category' => 'vereniging', 'sub_category' => 'contact']) ?>"><?= $this->translate('Contact') ?></a>
                        <a class="dropdown-item" href="<?= $this->url('home/page', ['category' => 'links']) ?>"><?= $this->translate('Links') ?></a>
                    </div>
                </li>
                
                <li class="nav-item dropdown <?= $this->moduleIsActive(['company']) ? 'active default' : '' ?>">
                    <a href="#" class="nav-link dropdown-toggle d-lg-none" role="button" id="companiesDropdown" data-toggle="dropdown" aria-expanded="false">
                        <?= $this->translate('Companies') ?>
                    </a>
                    <a href="<?= $this->url('company') ?>" class="nav-link dropdown-hover d-none d-lg-block" role="button">
                        <?= $this->translate('Companies') ?>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="companiesDropdown">
                        <a href="<?= $this->url('company') ?>" class="dropdown-item d-lg-none">
                            <?= $this->translate('Companies') ?>
                        </a>
                        <?php if (!is_null($this->featuredCompanyPackage())): ?>
                            <a href="<?= $this->url('company/spotlight') ?>" class="dropdown-item">
                                <span class="fas fa-star"></span>
                                <?= $this->translate('Featured') ?>:
                                <?= $this->featuredCompanyPackage()->getCompany()->getName() ?>
                            </a>
                        <?php endif; ?>
                        <?php foreach ($this->jobCategories() as $category ): ?>
                            <a href="<?=$this->url('company/jobList', ['category' => $category->getSlug()]) ?>" class="dropdown-item"><?= $category->getPluralName() ?></a>
                        <?php endforeach; ?>
                    </div>
                </li>
                
                <li class="nav-item <?= $this->moduleIsActive(['education']) ? 'active' : '' ?>">
                    <a href="<?= $this->url('education') ?>" class="nav-link"><?= $this->translate('Education') ?></a>
                </li>
                
                <li class="nav-item dropdown <?= $this->moduleIsActive(['activity']) ? 'active default' : '' ?>">
                    <a href="#" class="nav-link dropdown-toggle d-lg-none" role="button" id="activitiesDropdown" data-toggle="dropdown" aria-expanded="false">
                        <?= $this->translate('Activities') ?>
                    </a>
                    <a href="<?= $this->url('activity') ?>" class="nav-link dropdown-hover d-none d-lg-block" role="button">
                        <?= $this->translate('Activities') ?>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="activitiesDropdown">
                        <a href="<?= $this->url('activity') ?>" class="dropdown-item d-lg-none">
                            <?= $this->translate('Activities') ?>
                        </a>
                        <?php if ($this->acl('activity_acl')->isAllowed('activity', 'view')): ?>
                            <a class="dropdown-item" href="<?= $this->url('activity/my') ?>"> <?= $this->translate('My activities') ?></a>
                        <?php endif; ?>
                        <?php if ($this->acl('activity_acl')->isAllowed('activity', 'view')): ?>
                            <a class="dropdown-item" href="<?= $this->url('activity/archive') ?>"> <?= $this->translate('Activity Archive') ?></a>
                        <?php endif; ?>
                        <?php if ($this->acl('activity_acl')->isAllowed('activity', 'create')): ?>
                            <a class="dropdown-item" href="<?= $this->url('activity/create') ?>"> <?= $this->translate('Create an activity') ?></a>
                        <?php endif; ?>
                        <a href="https://gewis.nl/activity/corona"> <?= $this->translate('Activity Information COVID-19') ?></a>
                        <?php if ($this->acl('activity_acl')->isAllowed('activity', 'create')): ?>
                            <a class="dropdown-item" href="<?= $this->url('activity_calendar') ?>"> <?= $this->translate('Option calendar') ?></a>
                        <?php endif; ?>
                            <a class="dropdown-item" href="<?= $this->url('activity/career') ?>"> <?= $this->translate('Career related') ?></a>
                    </div>
                </li>
                
                <li class="nav-item dropdown <?= $this->moduleIsActive(['photo']) ? 'active' : '' ?>">
                    <?php if ($this->acl('photo_acl')->isAllowed('photo','view')): ?>
                        <a href="#" class="nav-link dropdown-toggle d-lg-none" role="button" id="photosDropdown" data-toggle="dropdown" aria-expanded="false">
                            <?= $this->translate('Photos') ?>
                        </a>
                        <a href="<?= $this->url('photo') ?>" class="nav-link dropdown-hover d-none d-lg-block" role="button">
                            <?= $this->translate('Photos') ?>
                        </a>
                    <?php else: ?>
                        <a href="<?= $this->url('photo') ?>" class="nav-link">
                            <?= $this->translate('Photos') ?>
                        </a>
                    <?php endif; ?>
                    <?php if ($this->acl('photo_acl')->isAllowed('photo','view')): ?>
                        <div class="dropdown-menu" aria-labelledby="photosDropdown">
                            <a href="<?= $this->url('photo') ?>" class="dropdown-item d-lg-none">
                                <?= $this->translate('Photos') ?>
                            </a>
                            <a class="dropdown-item" href="<?= $this->url('photo/weekly') ?>"><?= $this->translate('Photo of the week') ?></a>
                            <?php if (null != $this->identity()): ?>
                                <a class="dropdown-item" href="<?= $this->url('photo/member', ['lidnr' => $this->identity()->getMember()->getLidnr(), 'page' => null]) ?>">
                                    <?= $this->translate('My photo\'s') ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    <?php endif;?>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <?php if (null != $this->identity()): ?>
                    <li class="nav-item <?= $this->moduleIsActive(['decision']) ? 'active' : '' ?>">
                        <a href="<?= $this->url('member') ?>" class="nav-link"><?= $this->translate('Members') ?></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>