<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('user'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-signin w-100 p-4');
?>
<div class="col-md-4 offset-md-4">
    <div class="card mb-3">
        <?= $this->form()->openTag($form) ?>
            <div class="text-center mb-4">
                <h4 class="card-title"><?= $this->translate('Login') ?></h4>
            </div>

            <div class="form-label-group mb-2">
                <?php
                $element = $form->get('login');
                $element->setAttribute('id', 'login')
                        ->setAttribute('class', 'form-control' . (count($element->getMessages()) > 0 ? ' is-invalid' : ''))
                        ->setAttribute('placeholder', $element->getLabel());
                ?>
                <?= $this->formInput($element) ?>
                <label for="login"><?= $element->getLabel() ?></label>
                <?= $this->formElementErrors($element, array('class' => 'invalid-feedback')); ?>
            </div>

            <div class="form-label-group mb-2">
                <?php
                $element = $form->get('password');
                $element->setAttribute('id', 'password')
                        ->setAttribute('class', 'form-control' . (count($element->getMessages()) > 0 ? ' is-invalid' : ''))
                        ->setAttribute('placeholder', $element->getLabel());
                ?>
                <?= $this->formInput($element) ?>
                <label for="password"><?= $element->getLabel() ?></label>
                <?= $this->formElementErrors($element, array('class' => 'invalid-feedback')); ?>
            </div>

            <div class="form-check mb-2">
                <?php
                $element = $form->get('remember');
                $element->setAttribute('id', 'remember')
                        ->setAttribute('class', 'form-check-input')
                        ->setAttribute('checked', 'checked');
                ?>
                <?= $this->formCheckbox($element) ?>
                <label class="form-check-label" for="remember"><?= $element->getLabel() ?></label>
            </div>
            
            <?= $this->formInput($form->get('redirect')) ?>

            <?php
            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-lg btn-primary btn-block');
            ?>
            <?= $this->formSubmit($submit); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
    <div class="card">
        <div class="card-body bg-white">
            <p class="card-text">
                <?= sprintf($this->translate("If you don't have an account yet, go to the %sRegistration page%s"), '<a href="' . $this->url('user/default', ['action' => 'register']) . '">', '</a>') ?>.
                <?= sprintf($this->translate("If you forgot your password, go to the %sPassword reset page%s"), '<a href="' . $this->url('user/default', ['action' => 'reset']) . '">', '</a>') ?>.</p>
        </div>
    </div>
</div>