<?php
$this->headTitle($this->translate('Activate'));
?>
<section class="section py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card mb-3">
                    <div class="text-center m-4">
                        <h4 class="card-title m-0"><?= $this->translate('Activate') ?></h4>
                    </div>
                    <?php if (isset($this->activated) && $this->activated): ?>
                        <p class="card-text w-100 px-4 mb-4"><?= $this->translate('Your account has been activated. You are now able to login.') ?></p>
                    <?php else: ?>
                        <?php
                        $form = $this->form;
                        $form->prepare();

                        $form->setAttribute('action', $this->url('user/activate', ['code' => $this->user->getCode()]));
                        $form->setAttribute('method', 'post');

                        $form->setAttribute('role', 'form');
                        $form->setAttribute('class', 'form-activate w-100 p-4 pt-0');
                        ?>
                        <p class="card-text w-100 px-4">
                            <?php
                            $member = $this->user->getMember();
                            $name = $member->getFirstName() . ' ' . $member->getLastName();
                            ?>
                            <?= sprintf($this->translate("Welcome %s. Create your password for the website and activate your account."), $name) ?>
                        </p>

                        <?= $this->form()->openTag($form) ?>
                            <?php foreach (['password', 'password_verify'] as $field): ?>
                                <?php
                                $element = $form->get($field);
                                $element->setAttribute('id', $field)
                                        ->setAttribute('class', 'form-control' . (count($element->getMessages()) > 0 ? ' is-invalid' : ''))
                                        ->setAttribute('placeholder', $element->getLabel());
                                ?>
                                <div class="form-label-group mb-2">
                                    <?= $this->formInput($element) ?>
                                    <label for="<?= $element->getAttribute('id') ?>"><?= $element->getLabel() ?></label>
                                    <?= $this->formElementErrors($element, array('class' => 'invalid-feedback')); ?>
                                </div>
                            <?php endforeach; ?>

                            <?php
                            $submit = $form->get('submit');
                            $submit->setAttribute('class', 'btn btn-primary btn-block');
                            ?>
                            <div class="d-grid col-12 mx-auto">
                                <?= $this->formSubmit($submit); ?>
                            </div>
                        <?= $this->form()->closeTag(); ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>
