<?php
$this->headTitle($this->translate('Login'));
?>
<section class="section py-4">
    <div class="container">
        <div class="row">
            <?php if (isset($this->login) && $this->login): ?>
                <?= $this->translate('You are logged in.') ?>
            <?php else: ?>
                <?= $this->partial('partial/login.phtml', ['form' => $form]) ?>
            <?php endif; ?>
        </div>
    </div>
</section>
