<?php
$this->headTitle($this->translate('Register'));
?>
<section class="section py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card mb-3">
                    <div class="text-center m-4">
                        <h4 class="card-title m-0"><?= $this->translate('Register') ?></h4>
                    </div>
                    <?php if (isset($this->registered) && $this->registered): ?>
                        <p class="card-text w-100 px-4 mb-4"><?= sprintf($this->translate('You have been registered. An email has been sent to %s for activation.'), $this->user->getEmail()) ?></p>
                    <?php else: ?>
                        <?php
                        $form = $this->form;
                        $form->prepare();

                        $form->setAttribute('action', $this->url('user/default', ['action' => 'register']));
                        $form->setAttribute('method', 'post');

                        $form->setAttribute('role', 'form');
                        $form->setAttribute('class', 'form-register w-100 p-4 pt-0');
                        ?>

                        <?= $this->form()->openTag($form) ?>
                            <?php foreach (['lidnr', 'email'] as $field): ?>
                                <?php
                                $element = $form->get($field);
                                $element->setAttribute('id', $field)
                                        ->setAttribute('class', 'form-control' . (count($element->getMessages()) > 0 ? ' is-invalid' : ''))
                                        ->setAttribute('placeholder', $element->getLabel());
                                ?>
                                <div class="form-label-group mb-2">
                                    <?= $this->formInput($element) ?>
                                    <label for="<?= $element->getAttribute('id') ?>"><?= $element->getLabel() ?></label>
                                    <?= $this->formElementErrors($element, array('class' => 'invalid-feedback')); ?>
                                </div>
                            <?php endforeach; ?>

                            <?php
                            $submit = $form->get('submit');
                            $submit->setAttribute('class', 'btn btn-primary btn-block');
                            ?>
                            <?= $this->formSubmit($submit); ?>
                        <?= $this->form()->closeTag(); ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</section>
