<?= $this->doctype(); ?>

<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('GEWIS Website'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet('https://fonts.googleapis.com/css?family=Raleway:600,500,400|Lato:400,700,400italic')
            ->prependStylesheet($this->basePath() . '/css/font-awesome.css?v=1.4.1')
            ->prependStylesheet($this->basePath() . '/css/gewis-theme.css?v=1.4.1') ?>

        <!-- Scripts -->
        <?= $this->headScript()
            //->prependFile($this->basePath() . '/js/jquery.min.js')
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', ['conditional' => 'lt IE 9',])
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath() . '/js/url-helper.js')
        ; ?>

    </head>
    <body class="d-flex flex-column h-100">
        <?= $this->partial('partial/main-nav.phtml') ?>

        <main class="content-container">
            <?php $viewModel = current($this->viewModel()->getCurrent()->getChildren());
                if(strstr($viewModel->getTemplate(), 'admin')) {
                    echo $this->partial('partial/admin-nav.phtml', ['content' => $this->content]);
                } else {
                    echo $this->content;
                }
             ?>
        </main>

        <?= $this->partial('partial/footer.phtml') ?>

        <?= $this->inlineScript()
            ->prependFile($this->basePath() . '/js/bootstrap.bundle.min.js')
        ; ?>
        <script>
            <?php foreach($this->scriptUrl()->getUrls() as $name => $url): ?>
            URLHelper.addUrl('<?= $name ?>', '<?= urldecode($url) ?>');
            <?php endforeach; ?>
        </script>
    </body>
</html>
